return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  config = function()
    local config = require("nvim-treesitter.configs")
    config.setup({
      auto_install = true,
      sync_install = true,
      ensure_installed = {
        "angular",
        "arduino",
        "bash",
        "c",
        "c_sharp",
        "cmake",
        "comment",
        "cpp",
        "css",
        "csv",
        "dart",
        "dockerfile",
        "elixir",
        "elm",
        "erlang",
        "git_config",
        "git_rebase",
        "gitcommit",
        "gitignore",
        "go",
        "gomod",
        "gosum",
        "gotmpl",
        "graphql",
        "groovy",
        "html",
        "http",
        "java",
        "javascript",
        "jsdoc",
        "json",
        "json5",
        "kotlin",
        "lua",
        "luadoc",
        "make",
        "markdown",
        "markdown_inline",
        "pug",
        "python",
        "query",
        "r",
        "regex",
        "ruby",
        "rust",
        "scala",
        "scss",
        "sql",
        "ssh_config",
        "styled",
        "svelte",
        "typescript",
        "vim",
        "vimdoc",
        "vue",
        "xml",
        "yaml",
        "zig",
        "qmljs",
      },
      highlight = { enable = true },
      indent = { enable = true },
    })
  end,
}
